### ISSUE TITLE
Incompatibility with Vampirism (worlds can't load)

### ISSUE THREAD

**Issue by SpencerMeow** [freeeranger/dark-caverns#2]
Description: Ticking memory connection

java.lang.ClassCastException: com.freeranger.dark_caverns.capabilities.DefaultGatewayCooldown cannot be cast to de.teamlapen.vampirism.entity.factions.FactionPlayerHandler
	at de.teamlapen.vampirism.player.ModPlayerEventHandler$$Lambda$31580/413509266.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[?:?] {re:mixin,re:classloading}
	at de.teamlapen.vampirism.player.ModPlayerEventHandler.onPlayerName(ModPlayerEventHandler.java:283) ~[?:1.7.12] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_3959_ModPlayerEventHandler_onPlayerName_NameFormat.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2471/1832479838.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getPlayerDisplayName(ForgeEventFactory.java:268) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_145748_c_(PlayerEntity.java:1757) ~[?:?]

**Comment by freeeranger** [comment]
Hmm I think know whats causing this. I'll try fixing it later today

**Comment by freeeranger** [comment]
Uploading a hotfix now that should fix the issue. Let me know if you have any further problems!
